# Generated by Django 5.0 on 2026-02-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_add_customer_invite_and_fields'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_ASSIGNED', 'Order Assigned to Driver'), ('ORDER_PICKED_UP', 'Driver Picked Up Order'), ('ORDER_IN_TRANSIT', 'Order In Transit'), ('ORDER_ARRIVED', 'Driver Arrived'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('WALLET_TOPUP', 'Wallet Top-Up Successful'), ('WALLET_LOW_BALANCE', 'Low Wallet Balance'), ('REFUND_PROCESSED', 'Refund Processed'), ('BOTTLES_LOW', 'Low Bottle Inventory'), ('BOTTLES_EMPTY', 'No Empty Bottles'), ('BOTTLE_EXCHANGE', 'Bottle Exchange Completed'), ('BOTTLE_DEPOSIT', 'Bottle Deposit Received'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_NEARBY', 'Driver Nearby'), ('DRIVER_WAITING', 'Driver Waiting'), ('PROMOTION', 'Special Promotion'), ('DISCOUNT', 'Discount Available'), ('REFERRAL_REWARD', 'Referral Reward'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('ACCOUNT_UPDATE', 'Account Update'), ('MAINTENANCE', 'Scheduled Maintenance')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title/subject', max_length=200)),
                ('message', models.TextField(help_text='Notification message/body')),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Notification priority level', max_length=10)),
                ('send_push', models.BooleanField(default=True, help_text='Send as push notification')),
                ('send_sms', models.BooleanField(default=False, help_text='Send as SMS')),
                ('send_email', models.BooleanField(default=False, help_text='Send as email')),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('push_sent', models.BooleanField(default=False, help_text='Push notification sent successfully')),
                ('push_sent_at', models.DateTimeField(blank=True, help_text='When push notification was sent', null=True)),
                ('sms_sent', models.BooleanField(default=False, help_text='SMS sent successfully')),
                ('sms_sent_at', models.DateTimeField(blank=True, help_text='When SMS was sent', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Email sent successfully')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When email was sent', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when notification is clicked', max_length=500)),
                ('action_label', models.CharField(blank=True, help_text="Label for action button (e.g., 'View Order')", max_length=50)),
                ('extra_data', models.JSONField(blank=True, help_text='Additional notification data (JSON)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires and can be hidden', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer receiving this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Related order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
