# Generated by Django 5.0 on 2026-02-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Related wallet transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='wallet.wallettransaction'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['customer', '-created_at'], name='notificatio_custome_9085a1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['customer', 'is_read'], name='notificatio_custome_ba9e66_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_17ee5f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['order'], name='notificatio_order_i_25eb33_idx'),
        ),
    ]
