# Generated by Django 5.0 on 2026-04-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_creditterms_account_frozen_creditterms_frozen_at_and_more'),
        ('notifications', '0002_initial'),
        ('orders', '0003_order_created_by_admin_order_is_manual_order_and_more'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer receiving this notification. NULL for staff/driver-only alerts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_ASSIGNED', 'Order Assigned to Driver'), ('ORDER_PICKED_UP', 'Driver Picked Up Order'), ('ORDER_IN_TRANSIT', 'Order In Transit'), ('ORDER_ARRIVED', 'Driver Arrived'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('WALLET_TOPUP', 'Wallet Top-Up Successful'), ('WALLET_LOW_BALANCE', 'Low Wallet Balance'), ('REFUND_PROCESSED', 'Refund Processed'), ('BOTTLES_LOW', 'Low Bottle Inventory'), ('BOTTLES_EMPTY', 'No Empty Bottles'), ('BOTTLE_EXCHANGE', 'Bottle Exchange Completed'), ('BOTTLE_DEPOSIT', 'Bottle Deposit Received'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_NEARBY', 'Driver Nearby'), ('DRIVER_WAITING', 'Driver Waiting'), ('DELIVERY_OTP', 'Delivery OTP'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('STOCK_PICKUP', 'Stock Pickup Scheduled'), ('PROMOTION', 'Special Promotion'), ('DISCOUNT', 'Discount Available'), ('REFERRAL_REWARD', 'Referral Reward'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('ACCOUNT_UPDATE', 'Account Update'), ('MAINTENANCE', 'Scheduled Maintenance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='wallet.wallettransaction'),
        ),
    ]
