# Generated by Django 5.0 on 2026-02-22 12:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number', max_length=50)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted by Driver'), ('REJECTED', 'Rejected by Driver'), ('PICKED_UP', 'Picked Up from Warehouse'), ('EN_ROUTE', 'En Route to Customer'), ('ARRIVED', 'Arrived at Location'), ('IN_PROGRESS', 'Delivery In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='ASSIGNED', help_text='Current delivery status', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When delivery was assigned to driver')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When driver accepted the delivery', null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, help_text='When driver picked up bottles from warehouse', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When driver started heading to customer', null=True)),
                ('arrived_at', models.DateTimeField(blank=True, help_text='When driver arrived at customer location', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When delivery was completed', null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, help_text='Estimated time of arrival at customer location', null=True)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated delivery duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, help_text="Driver's current GPS latitude", max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, help_text="Driver's current GPS longitude", max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, help_text='When GPS location was last updated', null=True)),
                ('distance_to_customer', models.DecimalField(blank=True, decimal_places=2, help_text='Current distance to customer in kilometers', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_distance_travelled', models.DecimalField(blank=True, decimal_places=2, help_text='Total distance travelled for this delivery in kilometers', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('signature_image', models.ImageField(blank=True, help_text="Customer's signature", null=True, upload_to='delivery_signatures/%Y/%m/%d/')),
                ('photo_proof', models.ImageField(blank=True, help_text='Photo of delivered bottles', null=True, upload_to='delivery_photos/%Y/%m/%d/')),
                ('customer_name_confirmed', models.CharField(blank=True, help_text='Name of person who received delivery', max_length=100)),
                ('has_issues', models.BooleanField(default=False, help_text='Whether there were any issues during delivery')),
                ('issue_description', models.TextField(blank=True, help_text='Description of any issues encountered')),
                ('driver_notes', models.TextField(blank=True, help_text='Notes from driver about the delivery')),
                ('failure_reason', models.CharField(blank=True, choices=[('CUSTOMER_UNAVAILABLE', 'Customer Not Available'), ('WRONG_ADDRESS', 'Wrong/Invalid Address'), ('CUSTOMER_CANCELLED', 'Customer Cancelled'), ('VEHICLE_BREAKDOWN', 'Vehicle Breakdown'), ('WEATHER', 'Bad Weather'), ('TRAFFIC', 'Heavy Traffic'), ('OTHER', 'Other Reason')], help_text='Reason for delivery failure', max_length=30)),
                ('failure_notes', models.TextField(blank=True, help_text='Additional details about failure')),
                ('retry_scheduled', models.BooleanField(default=False, help_text='Whether a retry delivery is scheduled')),
                ('on_time', models.BooleanField(blank=True, help_text='Whether delivery was on time', null=True)),
                ('customer_rating', models.IntegerField(blank=True, help_text='Customer rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer_feedback', models.TextField(blank=True, help_text='Customer feedback about delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='Driver handling this delivery', limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='Order being delivered', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tracking', to='orders.order')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', '-created_at'], name='deliveries_driver__90c039_idx'), models.Index(fields=['status'], name='deliveries_status_c2a7cc_idx'), models.Index(fields=['assigned_at'], name='deliveries_assigne_18084a_idx'), models.Index(fields=['order'], name='deliveries_order_i_744a2b_idx')],
            },
        ),
    ]
