# Generated by Django 5.0 on 2026-03-04 09:55

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0002_alter_bottleexchange_options_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Scheduled delivery date', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='scheduled_time_slot',
            field=models.CharField(blank=True, default='', help_text="Scheduled delivery time slot (e.g. '10:00 AM – 12:00 PM')", max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer_name_confirmed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='distance_to_customer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='driver_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='failure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('CUSTOMER_UNAVAILABLE', 'Customer Not Available'), ('WRONG_ADDRESS', 'Wrong/Invalid Address'), ('CUSTOMER_CANCELLED', 'Customer Cancelled'), ('VEHICLE_BREAKDOWN', 'Vehicle Breakdown'), ('WEATHER', 'Bad Weather'), ('TRAFFIC', 'Heavy Traffic'), ('OTHER', 'Other Reason')], max_length=30),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='has_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='issue_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='on_time',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='photo_proof',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='retry_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_signatures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='total_distance_travelled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver', 'scheduled_date'], name='deliveries_driver__f6de2c_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['scheduled_date'], name='deliveries_schedul_f79d1b_idx'),
        ),
    ]
