# Generated by Django 5.0 on 2026-03-12 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_scheduled_date_delivery_scheduled_time_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='6-digit OTP shown to the customer', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='True once the driver enters the correct code')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when the driver verified the OTP', null=True)),
                ('expires_at', models.DateTimeField(help_text='OTP becomes invalid after this time (default 24 h from creation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.OneToOneField(help_text='The delivery this OTP belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='deliveries.delivery')),
            ],
            options={
                'verbose_name': 'Delivery OTP',
                'verbose_name_plural': 'Delivery OTPs',
                'db_table': 'delivery_otps',
            },
        ),
    ]
