# Generated by Django 5.0 on 2026-04-21 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_deliveryotp'),
        ('products', '0009_alter_bottlemovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Driver notes to the store')),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_requests', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to='deliveries.delivery')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('bottle', 'Bottle (returnable)'), ('consumable', 'Consumable')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_approved', models.PositiveIntegerField(blank=True, null=True)),
                ('current_qty_at_request', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_request_items', to='products.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.stockrequest')),
            ],
            options={
                'db_table': 'stock_request_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['driver', '-created_at'], name='stock_reque_driver__40ff53_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['status', '-created_at'], name='stock_reque_status_bd682a_idx'),
        ),
    ]
