# Generated by Django 5.0 on 2026-02-22 12:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('customers', '0002_add_customer_invite_and_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order number (e.g., ORD-2025-000001)', max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('REFILL', 'Bottle Refill'), ('NEW_BOTTLE', 'New Bottle Purchase'), ('MIXED', 'Refill + New Bottles')], help_text='Type of order', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned to Driver'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived at Location'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current order status', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal before delivery fee', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery charge', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied to order', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total amount (subtotal + delivery - discount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(choices=[('WALLET', 'Wallet'), ('CASH', 'Cash on Delivery'), ('CARD', 'Card Payment'), ('MPESA', 'M-Pesa')], default='WALLET', help_text='Payment method used', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special delivery instructions from customer')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When order was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When order was completed', null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Who cancelled the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Distributor/client handling this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
                ('customer', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BottleExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottles_to_deliver', models.IntegerField(default=0, help_text='Number of full bottles to deliver', validators=[django.core.validators.MinValueValidator(0)])),
                ('bottles_to_collect', models.IntegerField(default=0, help_text='Number of empty bottles to collect', validators=[django.core.validators.MinValueValidator(0)])),
                ('bottles_delivered', models.IntegerField(blank=True, help_text='Actual number of full bottles delivered', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bottles_collected', models.IntegerField(blank=True, help_text='Actual number of empty bottles collected', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('damaged_bottles', models.IntegerField(default=0, help_text='Number of damaged bottles found', validators=[django.core.validators.MinValueValidator(0)])),
                ('missing_bottles', models.IntegerField(default=0, help_text="Number of bottles customer couldn't find", validators=[django.core.validators.MinValueValidator(0)])),
                ('exchange_confirmed', models.BooleanField(default=False, help_text='Whether exchange was confirmed by driver')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When exchange was confirmed', null=True)),
                ('exchange_notes', models.TextField(blank=True, help_text='Notes about the exchange (issues, discrepancies, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Driver who confirmed the exchange', limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_exchanges', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='Order with bottle exchange', on_delete=django.db.models.deletion.CASCADE, related_name='bottle_exchange', to='orders.order')),
            ],
            options={
                'verbose_name': 'Bottle Exchange',
                'verbose_name_plural': 'Bottle Exchanges',
                'db_table': 'bottle_exchanges',
            },
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Scheduled delivery date')),
                ('scheduled_time_slot', models.CharField(help_text="Time slot for delivery (e.g., '9:00 AM - 12:00 PM')", max_length=50)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When driver was assigned', null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, help_text='When delivery was actually completed', null=True)),
                ('signature_image', models.ImageField(blank=True, help_text='Customer signature image', null=True, upload_to='delivery_signatures/')),
                ('photo_proof', models.ImageField(blank=True, help_text='Photo of delivered bottles', null=True, upload_to='delivery_photos/')),
                ('delivery_notes', models.TextField(blank=True, help_text='Notes from driver about delivery')),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude of delivery location', max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude of delivery location', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, help_text='Driver assigned to this delivery', limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(help_text='Address where order should be delivered', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='customers.customeraddress')),
                ('order', models.OneToOneField(help_text='Order being delivered', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Delivery',
                'verbose_name_plural': 'Order Deliveries',
                'db_table': 'order_deliveries',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('REFILL_19L', '19L Refill'), ('REFILL_15L', '15L Refill'), ('NEW_BOTTLE_19L', '19L New Bottle'), ('NEW_BOTTLE_15L', '15L New Bottle'), ('DISPENSER', 'Water Dispenser'), ('OTHER', 'Other Item')], help_text='Type of item ordered', max_length=30)),
                ('quantity', models.IntegerField(help_text='Number of items ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Total for this item (quantity × unit_price)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deposit_per_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit amount per item (for new bottles)', max_digits=8)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deposit for this item (quantity × deposit_per_item)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned to Driver'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived at Location'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], help_text='Status at this point in timeline', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this status was set')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this status change')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Timeline Entry',
                'verbose_name_plural': 'Order Timeline Entries',
                'db_table': 'order_timeline',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_custome_12b615_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', '-created_at'], name='orders_client__80fbb4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_payment_050188_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_created_b25042_idx'),
        ),
        migrations.AddIndex(
            model_name='bottleexchange',
            index=models.Index(fields=['order'], name='bottle_exch_order_i_2abdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='bottleexchange',
            index=models.Index(fields=['exchange_confirmed'], name='bottle_exch_exchang_85b7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['order'], name='order_deliv_order_i_b2ec89_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['assigned_driver', 'scheduled_date'], name='order_deliv_assigne_1dffd0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['scheduled_date'], name='order_deliv_schedul_da98c9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['item_type'], name='order_items_item_ty_9f3b66_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['order', 'timestamp'], name='order_timel_order_i_ead8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['status'], name='order_timel_status_2c0e68_idx'),
        ),
    ]
