# Generated by Django 5.0 on 2026-03-02 10:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('customers', '0004_creditterms_account_frozen_creditterms_frozen_at_and_more'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottleexchange',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderdelivery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordertimeline',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='bottleexchange',
            name='bottle_exch_exchang_85b7d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_created_b25042_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderdelivery',
            name='order_deliv_order_i_b2ec89_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_items_item_ty_9f3b66_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordertimeline',
            name='order_timel_status_2c0e68_idx',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='deposit_per_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_deposit',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Catalogue product this item refers to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, help_text='Product name at time of order (snapshot)', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_unit',
            field=models.CharField(blank=True, help_text='Unit (BOTTLES/LITRES) at time of order (snapshot)', max_length=10),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='bottles_collected',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='bottles_delivered',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='bottles_to_collect',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='bottles_to_deliver',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='damaged_bottles',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='exchange_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='exchange_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='missing_bottles',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bottleexchange',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_exchange', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('REFILL', 'Bottle Refill'), ('NEW_BOTTLE', 'New Bottle Purchase'), ('MIXED', 'Refill + New Bottles')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('CASH', 'Cash on Delivery'), ('CARD', 'Card Payment'), ('MPESA', 'M-Pesa')], default='WALLET', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned to Driver'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived at Location'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='customers.customeraddress'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='photo_proof',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_photos/'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='scheduled_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='scheduled_time_slot',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_signatures/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit at time of order', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ordertimeline',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordertimeline',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordertimeline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ordertimeline',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned to Driver'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived at Location'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertimeline',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
