# Generated by Django 5.0 on 2026-03-31 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_bottleexchange_options_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, help_text='Admin who placed this order on behalf of the customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='is_manual_order',
            field=models.BooleanField(default=False, help_text='True when a client admin places an order on behalf of a customer (phone/WhatsApp order)'),
        ),
        migrations.AddField(
            model_name='order',
            name='require_otp',
            field=models.BooleanField(default=True, help_text='If False, driver can complete delivery without customer OTP verification'),
        ),
    ]
