# Generated by Django 5.0 on 2026-03-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', help_text='Vehicle registration number (drivers only)', max_length=50),
        ),
    ]
