// src/pages/accounts/AccountingSettingsPage.tsx

import React, { useState, useEffect } from 'react';
import { toast } from 'sonner';
import { Loader2, Save, Building2, Receipt, CreditCard, Smartphone } from 'lucide-react';
import { accountingService } from '@/api/services/accounting.service';
import type { AccountingSettings } from '@/types/accounting.types';
import { AccountsLayout } from '@/pages/accounts/AccountsLayout';

const Section: React.FC<{
  icon: React.ReactNode;
  title: string;
  description: string;
  children: React.ReactNode;
}> = ({ icon, title, description, children }) => (
  <div className="rounded-2xl border border-border/60 bg-card overflow-hidden">
    <div className="px-5 py-4 border-b border-border/40 bg-muted/20 flex items-center gap-3">
      <div className="h-9 w-9 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0">
        {icon}
      </div>
      <div>
        <p className="font-bold text-sm">{title}</p>
        <p className="text-xs text-muted-foreground">{description}</p>
      </div>
    </div>
    <div className="p-5 space-y-4">{children}</div>
  </div>
);

const Field: React.FC<{
  label: string;
  required?: boolean;
  hint?: string;
  children: React.ReactNode;
}> = ({ label, required, hint, children }) => (
  <div className="space-y-1.5">
    <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
      {label}{required && <span className="text-destructive ml-1">*</span>}
    </label>
    {children}
    {hint && <p className="text-[11px] text-muted-foreground">{hint}</p>}
  </div>
);

const Input: React.FC<React.InputHTMLAttributes<HTMLInputElement>> = (props) => (
  <input
    {...props}
    className="w-full h-11 px-3.5 rounded-xl border border-border/60 bg-muted/30 text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/40 transition-colors"
  />
);

const Textarea: React.FC<React.TextareaHTMLAttributes<HTMLTextAreaElement>> = (props) => (
  <textarea
    {...props}
    className="w-full px-3.5 py-3 rounded-xl border border-border/60 bg-muted/30 text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/40 transition-colors resize-none"
  />
);

const EMPTY: AccountingSettings = {
  legalName: '',
  kraPin: '',
  vatRegistered: false,
  vatNumber: '',
  vatRate: 16,
  address: '',
  city: '',
  phone: '',
  email: '',
  invoicePrefix: 'INV',
  invoiceFooterNote: 'This is a computer-generated invoice. Goods once sold are not returnable.',
  bankName: '',
  bankAccountNumber: '',
  bankAccountName: '',
  bankBranch: '',
  mpesaPaybill: '',
  mpesaAccountName: '',
  mpesaTill: '',
};

export const AccountingSettingsPage: React.FC = () => {
  const [form,    setForm]    = useState<AccountingSettings>(EMPTY);
  const [loading, setLoading] = useState(true);
  const [saving,  setSaving]  = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const data = await accountingService.getSettings();
        setForm({ ...EMPTY, ...data });
      } catch {
        // No settings yet — defaults are fine
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const set = (key: keyof AccountingSettings, value: string | boolean | number) =>
    setForm(prev => ({ ...prev, [key]: value }));

  const handleSave = async () => {
    if (!form.legalName.trim()) { toast.error('Legal business name is required'); return; }
    if (!form.kraPin.trim())    { toast.error('KRA PIN is required'); return; }
    if (form.vatRegistered && !form.vatNumber.trim()) {
      toast.error('VAT registration number is required when VAT is enabled');
      return;
    }
    setSaving(true);
    try {
      await accountingService.saveSettings(form);
      toast.success('Accounting settings saved');
    } catch {
      toast.error('Failed to save settings');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-7 w-7 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <AccountsLayout title="Accounting Settings" subtitle="KRA, VAT, bank & M-Pesa configuration">
    <div className="max-w-2xl mx-auto space-y-5 pb-10 px-4 pt-6">

      <div className="mb-2">
        <h1 className="text-xl font-bold">Accounting Settings</h1>
        <p className="text-sm text-muted-foreground mt-0.5">
          These details appear on every invoice and receipt generated by your business.
        </p>
      </div>

      {/* Business Identity */}
      <Section
        icon={<Building2 className="h-4 w-4" />}
        title="Business Identity"
        description="Your legal business details for KRA compliance"
      >
        <Field label="Legal Business Name" required>
          <Input
            value={form.legalName}
            onChange={e => set('legalName', e.target.value)}
            placeholder="e.g. Pure Water Distributors Ltd"
          />
        </Field>

        <div className="grid grid-cols-2 gap-3">
          <Field label="KRA PIN" required hint="e.g. P0512345678A">
            <Input
              value={form.kraPin}
              onChange={e => set('kraPin', e.target.value.toUpperCase())}
              placeholder="P0512345678A"
            />
          </Field>
          <Field label="Invoice Prefix" hint="e.g. INV, RCP">
            <Input
              value={form.invoicePrefix}
              onChange={e => set('invoicePrefix', e.target.value.toUpperCase())}
              placeholder="INV"
              maxLength={6}
            />
          </Field>
        </div>

        <Field label="Physical Address" required>
          <Input
            value={form.address}
            onChange={e => set('address', e.target.value)}
            placeholder="Street address"
          />
        </Field>

        <div className="grid grid-cols-2 gap-3">
          <Field label="City / Town">
            <Input
              value={form.city}
              onChange={e => set('city', e.target.value)}
              placeholder="Nairobi"
            />
          </Field>
          <Field label="Phone">
            <Input
              value={form.phone}
              onChange={e => set('phone', e.target.value)}
              placeholder="+254712345678"
            />
          </Field>
        </div>

        <Field label="Email">
          <Input
            type="email"
            value={form.email}
            onChange={e => set('email', e.target.value)}
            placeholder="billing@yourcompany.co.ke"
          />
        </Field>
      </Section>

      {/* VAT */}
      <Section
        icon={<Receipt className="h-4 w-4" />}
        title="VAT & Tax"
        description="Configure how VAT appears on your invoices"
      >
        <div className="flex items-center justify-between py-1">
          <div>
            <p className="text-sm font-semibold">VAT Registered</p>
            <p className="text-xs text-muted-foreground mt-0.5">
              Turn on if your business is registered for VAT with KRA
            </p>
          </div>
          <button
            onClick={() => set('vatRegistered', !form.vatRegistered)}
            className={`relative h-6 w-11 rounded-full transition-colors ${
              form.vatRegistered ? 'bg-primary' : 'bg-muted-foreground/30'
            }`}
          >
            <span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition-transform ${
              form.vatRegistered ? 'translate-x-5' : 'translate-x-0.5'
            }`} />
          </button>
        </div>

        {form.vatRegistered ? (
          <div className="grid grid-cols-2 gap-3 pt-1">
            <Field label="VAT Reg Number" required hint="e.g. 00123456A">
              <Input
                value={form.vatNumber}
                onChange={e => set('vatNumber', e.target.value.toUpperCase())}
                placeholder="00123456A"
              />
            </Field>
            <Field label="VAT Rate (%)" hint="Standard rate is 16%">
              <Input
                type="number"
                value={form.vatRate}
                onChange={e => set('vatRate', parseFloat(e.target.value) || 16)}
                min={0}
                max={100}
              />
            </Field>
          </div>
        ) : (
          <div className="px-3 py-2.5 bg-muted/40 rounded-xl text-xs text-muted-foreground">
            Invoices will show <strong>"Exempt from VAT"</strong> — no VAT will be charged.
          </div>
        )}
      </Section>

      {/* Bank */}
      <Section
        icon={<CreditCard className="h-4 w-4" />}
        title="Bank Details"
        description="Shown on invoices for bank transfer payments"
      >
        <div className="grid grid-cols-2 gap-3">
          <Field label="Bank Name">
            <Input
              value={form.bankName}
              onChange={e => set('bankName', e.target.value)}
              placeholder="Equity Bank"
            />
          </Field>
          <Field label="Branch">
            <Input
              value={form.bankBranch}
              onChange={e => set('bankBranch', e.target.value)}
              placeholder="Westlands"
            />
          </Field>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <Field label="Account Number">
            <Input
              value={form.bankAccountNumber}
              onChange={e => set('bankAccountNumber', e.target.value)}
              placeholder="1234567890"
            />
          </Field>
          <Field label="Account Name">
            <Input
              value={form.bankAccountName}
              onChange={e => set('bankAccountName', e.target.value)}
              placeholder="Pure Water Ltd"
            />
          </Field>
        </div>
      </Section>

      {/* M-Pesa */}
      <Section
        icon={<Smartphone className="h-4 w-4" />}
        title="M-Pesa Details"
        description="Shown on invoices for M-Pesa payments"
      >
        <div className="grid grid-cols-2 gap-3">
          <Field label="Paybill Number">
            <Input
              value={form.mpesaPaybill}
              onChange={e => set('mpesaPaybill', e.target.value)}
              placeholder="247247"
            />
          </Field>
          <Field label="Account Name">
            <Input
              value={form.mpesaAccountName}
              onChange={e => set('mpesaAccountName', e.target.value)}
              placeholder="PureWater"
            />
          </Field>
        </div>
        <Field label="Till Number" hint="Leave blank if using Paybill">
          <Input
            value={form.mpesaTill}
            onChange={e => set('mpesaTill', e.target.value)}
            placeholder="123456"
          />
        </Field>
      </Section>

      {/* Footer note */}
      <Section
        icon={<Receipt className="h-4 w-4" />}
        title="Invoice Footer Note"
        description="Printed at the bottom of every invoice"
      >
        <Textarea
          rows={3}
          value={form.invoiceFooterNote}
          onChange={e => set('invoiceFooterNote', e.target.value)}
          placeholder="This is a computer-generated invoice..."
        />
      </Section>

      {/* Save */}
      <button
        onClick={handleSave}
        disabled={saving}
        className="w-full rounded-2xl bg-primary text-primary-foreground font-bold text-sm flex items-center justify-center gap-2 hover:bg-primary/90 disabled:opacity-50 transition-colors active:scale-[0.98]"
        style={{ height: '52px' }}
      >
        {saving
          ? <><Loader2 className="h-4 w-4 animate-spin" />Saving…</>
          : <><Save className="h-4 w-4" />Save Settings</>
        }
      </button>

    </div>
    </AccountsLayout>
  );
};

export default AccountingSettingsPage;