# Generated by Django 5.0 on 2026-03-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_footer_note', models.TextField(blank=True)),
                ('vat_registered', models.BooleanField(default=False)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=16.0, help_text='VAT rate as a percentage e.g. 16.00', max_digits=5)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=20)),
                ('mpesa_account_name', models.CharField(blank=True, max_length=100)),
                ('mpesa_till', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_settings', to='clients.client')),
            ],
            options={
                'verbose_name': 'Accounting Settings',
                'verbose_name_plural': 'Accounting Settings',
                'db_table': 'accounting_settings',
            },
        ),
    ]
