# Generated by Django 5.0 on 2026-02-22 12:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_add_customer_invite_and_fields'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current wallet balance', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_topped_up', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount ever topped up (lifetime)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount ever spent (lifetime)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum spending per day (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum spending per month (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('auto_topup_enabled', models.BooleanField(default=False, help_text='Enable automatic top-up when balance is low')),
                ('auto_topup_threshold', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Trigger auto top-up when balance falls below this amount', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('auto_topup_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Amount to add during auto top-up', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('low_balance_alert_enabled', models.BooleanField(default=True, help_text='Send notification when balance is low')),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Send alert when balance falls below this amount', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether wallet is active and can be used')),
                ('is_locked', models.BooleanField(default=False, help_text='Wallet locked (e.g., due to suspicious activity)')),
                ('locked_reason', models.TextField(blank=True, help_text='Reason for locking the wallet')),
                ('locked_at', models.DateTimeField(blank=True, help_text='When wallet was locked', null=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, help_text='When last transaction occurred', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(help_text='Customer who owns this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TOPUP', 'Top Up'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Manual Adjustment'), ('PENALTY', 'Penalty/Deduction'), ('BONUS', 'Bonus/Credit')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (always positive)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Wallet balance before this transaction', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after this transaction', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', help_text='Transaction status', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card Payment'), ('MPESA', 'M-Pesa'), ('BANK_TRANSFER', 'Bank Transfer'), ('SYSTEM', 'System Generated')], help_text='Payment method used', max_length=30, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='External payment reference (e.g., M-Pesa transaction ID)', max_length=100)),
                ('description', models.CharField(help_text='Brief description of transaction', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When transaction was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When transaction was completed', null=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated this transaction (for manual transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_initiated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Order this payment is for (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order')),
                ('wallet', models.ForeignKey(help_text='Wallet this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['customer'], name='wallets_custome_0488de_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_active'], name='wallets_is_acti_3744ed_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['current_balance'], name='wallets_current_ca0e25_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_tran_wallet__3d47ad_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='wallet_tran_transac_377ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='wallet_tran_status_c987ce_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['order'], name='wallet_tran_order_i_f9d811_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['-created_at'], name='wallet_tran_created_48133d_idx'),
        ),
    ]
