# Generated by Django 5.0 on 2026-02-03 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name', max_length=255)),
                ('email', models.EmailField(help_text='Company email', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Company phone number', max_length=20)),
                ('address', models.TextField(help_text='Street address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='logos/')),
                ('website', models.URLField(blank=True, help_text='Company website', max_length=255, null=True)),
                ('subscription_plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('trial', 'Trial'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, help_text='When subscription expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='clients_email_4c8bec_idx'), models.Index(fields=['subscription_status'], name='clients_subscri_60cc1a_idx')],
            },
        ),
    ]
