# Generated by Django 5.0 on 2026-02-03 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer OTP',
                'verbose_name_plural': 'Customer OTPs',
                'db_table': 'customer_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, help_text="Customer's phone number (used for login)", max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, help_text="Customer's email (optional)", max_length=254, null=True)),
                ('customer_type', models.CharField(choices=[('REFILL', 'Refill Customer'), ('ONETIME', 'One-time Purchase'), ('HYBRID', 'Hybrid')], default='REFILL', help_text='Refill or one-time purchase customer', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_order_date', models.DateTimeField(blank=True, help_text='Last time customer placed an order', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The distributor serving this customer', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='clients.client')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="E.g., 'Home', 'Office', 'Shop'", max_length=50)),
                ('address', models.TextField(help_text='Full delivery address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default delivery address')),
                ('delivery_instructions', models.TextField(blank=True, help_text="Special instructions for delivery (e.g., 'Call when arriving')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'db_table': 'customer_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_delivery_time', models.CharField(default='10:00 AM - 12:00 PM', help_text='Preferred delivery time slot', max_length=50)),
                ('delivery_instructions', models.TextField(blank=True, help_text='General delivery instructions')),
                ('sms_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Preferences',
                'verbose_name_plural': 'Customer Preferences',
                'db_table': 'customer_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_phone_n_7d2329_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['client', 'status'], name='customers_client__106216_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('client', 'phone_number')},
        ),
    ]
