# Generated by Django 5.0 on 2026-02-22 10:04

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customerotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customerpreferences',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='True once the customer has completed their registration via the invite link'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('REFILL', 'Refill Customer'), ('ONETIME', 'One-time Purchase'), ('HYBRID', 'Hybrid')], default='REFILL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text="Customer's email (used for invite / notifications)", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(db_index=True, help_text="Customer's phone number (used for login)", max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(help_text="E.g., 'Home', 'Office'", max_length=50),
        ),
        migrations.AlterField(
            model_name='customerpreferences',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerpreferences',
            name='preferred_delivery_time',
            field=models.CharField(default='10:00 AM - 12:00 PM', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomerInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Invite',
                'verbose_name_plural': 'Customer Invites',
                'db_table': 'customer_invites',
                'ordering': ['-created_at'],
            },
        ),
    ]
