# Generated by Django 5.0 on 2026-02-26 11:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('customers', '0002_add_customer_invite_and_fields'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinvite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CreditTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('IMMEDIATE', 'Per Order (Immediate)'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly (1st & 15th)'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Max outstanding unpaid balance allowed (KES)', max_digits=10)),
                ('payment_due_days', models.PositiveIntegerField(default=30, help_text='Days after invoice issue before it becomes overdue')),
                ('notes', models.TextField(blank=True, help_text="e.g. 'Pays by cheque end of month. Contact: Finance Dept.'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_terms', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Credit Terms',
                'db_table': 'customer_credit_terms',
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='e.g. CINV-2026-000042', max_length=60, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('IMMEDIATE', 'Per Order (Immediate)'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly (1st & 15th)'), ('MONTHLY', 'Monthly')], help_text="Snapshot of customer's billing cycle at generation time", max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('MPESA', 'M-Pesa')], max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Cheque number, bank ref, M-Pesa code, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Invoice',
                'db_table': 'customer_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.customerinvoice')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='orders.order')),
            ],
            options={
                'verbose_name': 'Customer Invoice Item',
                'db_table': 'customer_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mpesa_number', models.CharField(blank=True, help_text='M-Pesa phone (may differ from login phone)', max_length=20)),
                ('preferred_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Cash on Delivery'), ('WALLET', 'Wallet'), ('CREDIT', 'Credit Account (Pay Later)')], default='CASH', max_length=10)),
                ('credit_account_enabled', models.BooleanField(default=False, help_text='Distributor sets this — allows pay-later orders')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Max outstanding credit (KES)', max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current unpaid credit (KES)', max_digits=10)),
                ('setup_completed', models.BooleanField(default=False, help_text='True once the customer completes the payment setup step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Payment Profile',
                'db_table': 'customer_payment_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['customer', '-created_at'], name='customer_in_custome_9dcd13_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['status'], name='customer_in_status_fcf99d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['due_date'], name='customer_in_due_dat_971fb2_idx'),
        ),
    ]
