# Generated by Django 5.0 on 2026-02-27 12:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customerinvite_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditterms',
            name='account_frozen',
            field=models.BooleanField(default=False, help_text='True = account frozen, no new orders allowed'),
        ),
        migrations.AddField(
            model_name='creditterms',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditterms',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=7, help_text='Default grace window (days) after due date before account freezes'),
        ),
        migrations.AddField(
            model_name='creditterms',
            name='grace_until',
            field=models.DateField(blank=True, help_text='Grace deadline — account freezes if unpaid after this date', null=True),
        ),
        migrations.AddField(
            model_name='creditterms',
            name='original_credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agreed limit preserved for reset after payment.', max_digits=10),
        ),
        migrations.AddField(
            model_name='creditterms',
            name='overdue_since',
            field=models.DateField(blank=True, help_text='Date the first unpaid invoice went overdue (grace clock start)', null=True),
        ),
        migrations.AlterField(
            model_name='creditterms',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Active limit (KES). Resets to original_credit_limit after payment.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditterms',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='creditterms',
            name='payment_due_days',
            field=models.PositiveIntegerField(default=30, help_text='Days after invoice issue before overdue'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='billing_cycle',
            field=models.CharField(choices=[('IMMEDIATE', 'Per Order (Immediate)'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly (1st & 15th)'), ('MONTHLY', 'Monthly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='invoice_number',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='GracePeriodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_days', models.PositiveIntegerField(help_text='Extra days requested by the customer')),
                ('reason', models.TextField(help_text="Customer's explanation for needing more time")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, help_text="Admin's note shown to the customer after decision")),
                ('days_granted', models.PositiveIntegerField(blank=True, help_text='Actual days granted (admin may adjust from requested)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grace_requests', to='customers.creditterms')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grace_request_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grace Period Request',
                'db_table': 'grace_period_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
