# Generated by Django 5.0 on 2026-02-22 12:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_add_customer_invite_and_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_owned', models.IntegerField(default=0, help_text='Total number of bottles customer owns (purchased with deposit)', validators=[django.core.validators.MinValueValidator(0)])),
                ('full_bottles', models.IntegerField(default=0, help_text='Number of full bottles at customer location', validators=[django.core.validators.MinValueValidator(0)])),
                ('empty_bottles', models.IntegerField(default=0, help_text='Number of empty bottles at customer location', validators=[django.core.validators.MinValueValidator(0)])),
                ('in_transit', models.IntegerField(default=0, help_text='Bottles currently being delivered or collected', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deposit amount paid by customer for bottles', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deposit_per_bottle', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Standard deposit amount per bottle for this customer's client", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_transaction_date', models.DateTimeField(blank=True, help_text='When the last bottle transaction occurred', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(help_text='The customer who owns these bottles', on_delete=django.db.models.deletion.CASCADE, related_name='bottle_inventory', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Bottle Inventory',
                'verbose_name_plural': 'Bottle Inventories',
                'db_table': 'bottle_inventory',
            },
        ),
        migrations.CreateModel(
            name='BottleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Bottle Purchase'), ('DELIVERY', 'Bottle Delivery'), ('COLLECTION', 'Bottle Collection'), ('RETURN', 'Bottle Return'), ('DAMAGE', 'Bottle Damage/Loss'), ('ADJUSTMENT', 'Manual Adjustment')], help_text='Type of bottle transaction', max_length=20)),
                ('quantity', models.IntegerField(help_text='Number of bottles in this transaction', validators=[django.core.validators.MinValueValidator(1)])),
                ('balance_total_owned', models.IntegerField(default=0, help_text='Total owned bottles after this transaction')),
                ('balance_full', models.IntegerField(default=0, help_text='Full bottles after this transaction')),
                ('balance_empty', models.IntegerField(default=0, help_text='Empty bottles after this transaction')),
                ('balance_in_transit', models.IntegerField(default=0, help_text='In-transit bottles after this transaction')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit amount involved in this transaction', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this transaction was recorded')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottle_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer involved in this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='bottle_transactions', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Bottle Transaction',
                'verbose_name_plural': 'Bottle Transactions',
                'db_table': 'bottle_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
