# Generated by Django 5.0 on 2026-02-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bottles', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottletransaction',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order associated with this transaction (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottle_transactions', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='bottleinventory',
            index=models.Index(fields=['customer'], name='bottle_inve_custome_b0df75_idx'),
        ),
        migrations.AddIndex(
            model_name='bottleinventory',
            index=models.Index(fields=['last_transaction_date'], name='bottle_inve_last_tr_a19a55_idx'),
        ),
        migrations.AddIndex(
            model_name='bottletransaction',
            index=models.Index(fields=['customer', '-created_at'], name='bottle_tran_custome_c765d0_idx'),
        ),
        migrations.AddIndex(
            model_name='bottletransaction',
            index=models.Index(fields=['transaction_type'], name='bottle_tran_transac_c44d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='bottletransaction',
            index=models.Index(fields=['order'], name='bottle_tran_order_i_1ec44d_idx'),
        ),
        migrations.AddIndex(
            model_name='bottletransaction',
            index=models.Index(fields=['-created_at'], name='bottle_tran_created_b4ff32_idx'),
        ),
    ]
