# /apps/products/migrations/0001_initial.py
# Generated by Django 5.0 on 2026-03-01 05:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[
                 ('BOTTLES', 'Bottles'), ('LITRES', 'Litres')], default='BOTTLES', max_length=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price shown to customers (KES)',
                 max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buying_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price — visible to business owner only (KES)',
                 max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), (
                    'ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='products', to='clients.client')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(
                    help_text='Barcode scan or auto-generated SN-YYYYMMDD-XXXXX', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units received',
                 validators=[django.core.validators.MinValueValidator(1)])),
                ('batch_ref', models.CharField(
                    help_text='Auto-generated batch reference BATCH-YYYYMMDD-XXXX', max_length=50)),
                ('received_at', models.DateTimeField(
                    help_text='Date and time stock was physically received')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='stock_entries', to='products.product')),
                ('received_by', models.ForeignKey(help_text='Staff member who recorded this entry', null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_entries',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                fields=['client', 'status'], name='products_client__792d24_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(
                fields=['product', 'received_at'], name='stock_entri_product_948234_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(
                fields=['serial_number'], name='stock_entri_serial__faf96f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['batch_ref'],
                               name='stock_entri_batch_r_70f40e_idx'),
        ),
    ]
