# Generated by Django 5.0 on 2026-03-09 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_dozens_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockdistribution',
            new_name='stock_distr_product_772053_idx',
            old_name='stock_dist_product_date_idx',
        ),
        migrations.RenameIndex(
            model_name='stockdistribution',
            new_name='stock_distr_vehicle_bf00c7_idx',
            old_name='stock_dist_vehicle_date_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dozen_base_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dozen_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='dozen_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many bottles or litres make one dozen for this product. Required when unit=DOZENS, null otherwise.', null=True),
        ),
        migrations.AlterField(
            model_name='stockdistribution',
            name='distributed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_distributions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockdistribution',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_distributions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockdistribution',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='batch_ref',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Always 1 — each entry represents one physical unit.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='received_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
