# Generated by Django 5.0 on 2026-03-27 14:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('customers', '0004_creditterms_account_frozen_creditterms_frozen_at_and_more'),
        ('products', '0006_store_movements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBottleMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('DIRECT_SALE', 'Direct Sale'), ('DISTRIBUTE', 'Distribute to Van')], max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CREDIT', 'Credit')], default='CASH', max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_bottle_movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreConsumableMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('DIRECT_SALE', 'Direct Sale'), ('DISTRIBUTE', 'Distribute to Van')], max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CREDIT', 'Credit')], default='CASH', max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_consumable_movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='bottlemovement',
            new_name='bottle_move_product_f897f1_idx',
            old_name='bottle_mov_product_date_idx',
        ),
        migrations.RenameIndex(
            model_name='bottlemovement',
            new_name='bottle_move_movemen_df13eb_idx',
            old_name='bottle_mov_type_date_idx',
        ),
        migrations.RenameIndex(
            model_name='bottlemovement',
            new_name='bottle_move_driver__27c587_idx',
            old_name='bottle_mov_driver_date_idx',
        ),
        migrations.RenameIndex(
            model_name='consumablemovement',
            new_name='consumable__product_04cda3_idx',
            old_name='consumable_mov_product_date_idx',
        ),
        migrations.RenameIndex(
            model_name='consumablemovement',
            new_name='consumable__movemen_e03de4_idx',
            old_name='consumable_mov_type_date_idx',
        ),
        migrations.AlterField(
            model_name='bottlemovement',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Walk-in name if no customer account', max_length=200),
        ),
        migrations.AlterField(
            model_name='bottlemovement',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver involved (for RECEIVE_EMPTY or DISTRIBUTE)', limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottle_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bottlemovement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bottlemovement',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_returnable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bottle_movements', to='products.product'),
        ),
        migrations.AlterField(
            model_name='bottlemovement',
            name='qty_expected',
            field=models.PositiveIntegerField(default=0, help_text='Only used for RECEIVE_EMPTY. How many empties were expected from this driver.'),
        ),
        migrations.AlterField(
            model_name='bottlemovement',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Van plate — auto-filled from driver if available', max_length=20),
        ),
        migrations.AlterField(
            model_name='consumablemovement',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consumablemovement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consumablemovement',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Supplier name for RECEIVE movements', max_length=200),
        ),
        migrations.AlterField(
            model_name='consumablemovement',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price for DIRECT_SALE', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='True for returnable bottles (e.g. 18.9L dispensers). False for consumables.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('BOTTLES', 'Bottles'), ('LITRES', 'Litres'), ('DOZENS', 'Dozens'), ('PIECES', 'Pieces'), ('CRATES', 'Crates'), ('JERRICANS', 'Jerricans'), ('SACHETS', 'Sachets'), ('GALLONS', 'Gallons'), ('PACKS', 'Packs'), ('CARTONS', 'Cartons')], default='BOTTLES', max_length=10),
        ),
        migrations.AddField(
            model_name='storebottlemovement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bottle_movements', to='clients.client'),
        ),
        migrations.AddField(
            model_name='storebottlemovement',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_bottle_movements', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='storebottlemovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_bottle_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storebottlemovement',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_returnable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='store_bottle_movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='storeconsumablemovement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_consumable_movements', to='clients.client'),
        ),
        migrations.AddField(
            model_name='storeconsumablemovement',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_consumable_movements', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='storeconsumablemovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_consumable_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeconsumablemovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_consumable_movements', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='storebottlemovement',
            index=models.Index(fields=['client', 'movement_type', 'movement_date'], name='store_bottl_client__ae2af9_idx'),
        ),
        migrations.AddIndex(
            model_name='storebottlemovement',
            index=models.Index(fields=['product', 'movement_date'], name='store_bottl_product_82a6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='storeconsumablemovement',
            index=models.Index(fields=['client', 'movement_type', 'movement_date'], name='store_consu_client__7f54ca_idx'),
        ),
        migrations.AddIndex(
            model_name='storeconsumablemovement',
            index=models.Index(fields=['product', 'movement_date'], name='store_consu_product_f9b2f8_idx'),
        ),
    ]
