# Generated by Django 5.0 on 2026-04-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_storeconsumablemovement_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlemovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('RECEIVE_EMPTY', 'Receive Empties'), ('REFILL', 'Refill Empties'), ('DISTRIBUTE', 'Distribute to Van'), ('DIRECT_SALE', 'Direct Sale')], max_length=20),
        ),
    ]
